# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_crest_debugger.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 850))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1250, 850))
        self.tabWidget.setMinimumSize(QtCore.QSize(1250, 850))
        self.tabWidget.setMaximumSize(QtCore.QSize(1250, 850))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    min-width: 30ex;\n"
"    min-height: 6ex;\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.full_test_tab = QtWidgets.QWidget()
        self.full_test_tab.setObjectName("full_test_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.full_test_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1241, 821))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.full_test_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.full_test_Layout.setContentsMargins(0, 0, 0, 0)
        self.full_test_Layout.setObjectName("full_test_Layout")
        self.tabWidget.addTab(self.full_test_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.full_test_tab), _translate("MainWindow", "full_test"))
