# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_factory_test_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_factory_test_func(object):
    def setupUi(self, factory_test_func):
        factory_test_func.setObjectName("factory_test_func")
        factory_test_func.resize(1500, 900)
        factory_test_func.setMinimumSize(QtCore.QSize(1500, 900))
        factory_test_func.setMaximumSize(QtCore.QSize(1500, 900))
        self.verticalLayoutWidget = QtWidgets.QWidget(factory_test_func)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 661, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layout_deviceManage = QtWidgets.QHBoxLayout()
        self.Layout_deviceManage.setContentsMargins(-1, 0, -1, -1)
        self.Layout_deviceManage.setObjectName("Layout_deviceManage")
        self.label_currentDevice = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_currentDevice.setFont(font)
        self.label_currentDevice.setObjectName("label_currentDevice")
        self.Layout_deviceManage.addWidget(self.label_currentDevice)
        self.label_currDevAddr = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.label_currDevAddr.setFont(font)
        self.label_currDevAddr.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_currDevAddr.setObjectName("label_currDevAddr")
        self.Layout_deviceManage.addWidget(self.label_currDevAddr)
        self.Layout_deviceManage.setStretch(1, 5)
        self.verticalLayout.addLayout(self.Layout_deviceManage)
        self.Btn_connect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Blac")
        font.setPointSize(22)
        self.Btn_connect.setFont(font)
        self.Btn_connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_connect.setObjectName("Btn_connect")
        self.verticalLayout.addWidget(self.Btn_connect)
        self.listWidget_deviceList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget_deviceList.setObjectName("listWidget_deviceList")
        self.verticalLayout.addWidget(self.listWidget_deviceList)
        self.Btn_scanDevice = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Blac")
        font.setPointSize(22)
        self.Btn_scanDevice.setFont(font)
        self.Btn_scanDevice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_scanDevice.setObjectName("Btn_scanDevice")
        self.verticalLayout.addWidget(self.Btn_scanDevice)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(2, 100)

        self.retranslateUi(factory_test_func)
        QtCore.QMetaObject.connectSlotsByName(factory_test_func)

    def retranslateUi(self, factory_test_func):
        _translate = QtCore.QCoreApplication.translate
        factory_test_func.setWindowTitle(_translate("factory_test_func", "factory test function"))
        self.label_currentDevice.setText(_translate("factory_test_func", "C U R R E N T    D E V I C E:"))
        self.label_currDevAddr.setText(_translate("factory_test_func", "N/A"))
        self.Btn_connect.setText(_translate("factory_test_func", "C O N N E C T  >>"))
        self.Btn_scanDevice.setText(_translate("factory_test_func", "S C A N        D E V I C E"))
